### ISSUE TITLE
`SoftAssertionsExtension_PER_CLASS_Concurrency_Test` flaky test

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#1996]
#### Summary

`SoftAssertionsExtension_PER_CLASS_Concurrency_Test.concurrent_tests_with_explicit_per_class_annotation_do_not_interfere` is flaky. 

Here's a run with the test above failing (MacOS): [logs_1781.zip](https://github.com/joel-costigliola/assertj-core/files/5251438/logs_1781.zip).

Specific extract:
```
2020-09-20T10:12:40.2127020Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.055 s <<< FAILURE! - in org.assertj.core.api.junit.jupiter.SoftAssertionsExtension_PER_CLASS_Concurrency_Test
2020-09-20T10:12:40.2134720Z [ERROR] concurrent_tests_with_explicit_per_class_annotation_do_not_interfere  Time elapsed: 0.054 s  <<< ERROR!
2020-09-20T10:12:40.2139590Z java.lang.NullPointerException
2020-09-20T10:12:40.2270140Z 	at org.assertj.core.api.junit.jupiter.SoftAssertionsExtension_PER_CLASS_Concurrency_Test.concurrent_tests_with_explicit_per_class_annotation_do_not_interfere(SoftAssertionsExtension_PER_CLASS_Concurrency_Test.java:120)
2020-09-20T10:12:40.2287320Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-20T10:12:40.2381740Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-09-20T10:12:40.2384380Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-20T10:12:40.2386180Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-09-20T10:12:40.2387850Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
2020-09-20T10:12:40.2446080Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2020-09-20T10:12:40.2448810Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2020-09-20T10:12:40.2451190Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-09-20T10:12:40.2454330Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2020-09-20T10:12:40.2519330Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2020-09-20T10:12:40.2522170Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-09-20T10:12:40.2524510Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-09-20T10:12:40.2527620Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-09-20T10:12:40.2530510Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-09-20T10:12:40.2533610Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-09-20T10:12:40.2536690Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-09-20T10:12:40.2539170Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-09-20T10:12:40.2542120Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-09-20T10:12:40.2546100Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
2020-09-20T10:12:40.2558380Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2561430Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
2020-09-20T10:12:40.2565000Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
2020-09-20T10:12:40.2568120Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
2020-09-20T10:12:40.2574280Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
2020-09-20T10:12:40.2576950Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2581610Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-09-20T10:12:40.2583710Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-09-20T10:12:40.2585720Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-09-20T10:12:40.2588190Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2590930Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-09-20T10:12:40.2593420Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-09-20T10:12:40.2594880Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2020-09-20T10:12:40.2597790Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-09-20T10:12:40.2601500Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-09-20T10:12:40.2604010Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2606670Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-09-20T10:12:40.2608710Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-09-20T10:12:40.2610750Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-09-20T10:12:40.2618410Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2621220Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-09-20T10:12:40.2623750Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-09-20T10:12:40.2625250Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2020-09-20T10:12:40.2628850Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-09-20T10:12:40.2632650Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-09-20T10:12:40.2635180Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2637700Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2020-09-20T10:12:40.2639740Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2020-09-20T10:12:40.2641910Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2020-09-20T10:12:40.2644450Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-20T10:12:40.2647350Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2020-09-20T10:12:40.2671110Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2020-09-20T10:12:40.2674640Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-09-20T10:12:40.2678640Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-09-20T10:12:40.2682380Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-09-20T10:12:40.2684770Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2020-09-20T10:12:40.2686510Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2020-09-20T10:12:40.2688630Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2020-09-20T10:12:40.2690750Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2020-09-20T10:12:40.2692580Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2020-09-20T10:12:40.2694920Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2020-09-20T10:12:40.2697620Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
2020-09-20T10:12:40.2700280Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-09-20T10:12:40.2702730Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-09-20T10:12:40.2704550Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-09-20T10:12:40.2706070Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by joel-costigliola** [comment]
@kriegfrj is that something you have experienced?

**Comment by kriegfrj** [comment]
I've not seen it before and I don't have a Mac to test on, but I've just had a look over it and there are some potential memory visibility issues arising due to the non-thread-safe hashmap I'm using so I made it synchronized. I also broke down the chained call where the NPE was happening so we can better pinpoint where the null is when it occurs. See #1997.

Let's run with this and see what comes up.

**Comment by joel-costigliola** [comment]
I don't have a Mac neither ;-)

**Comment by scordio** [comment]
Feel free to ping me next time a mac issue arises 🙂

**Comment by joel-costigliola** [comment]
@kriegfrj build looks good so far :smiley:

**Comment by joel-costigliola** [comment]
Build is stable regarding soft assertions

**Comment by scordio** [comment]
We started getting flaky tests on 303704ef. The most recent change that could be related is at bcb4e142, but I don't see any reason why things got worse with it.

**Comment by danaebu** [comment]
Can I work on this?

**Comment by scordio** [comment]
Sure and thanks, @danaebu!

**Comment by danaebu** [comment]
The issue is caused by:
https://github.com/junit-team/junit-framework/issues/5171
As soon this issue is fixed and a new version is released, the JUnit version must be updated in assertj. This should fix this issue.

**Comment by scordio** [comment]
Impressive analysis, well done @danaebu and @martinfrancois!
