### ISSUE TITLE
SoftAssertions collects only first fail in case of Exceptions 

### ISSUE THREAD

**Issue by stefanhh0** [assertj/assertj#2699]
**Describe the bug**
SoftAssertions collects only first fail in case of Exceptions.

Output is:
```
[ERROR] SoftAssertionsTest.test  Time elapsed: 0.086 s  <<< FAILURE!
java.lang.AssertionError: 
[A] 
Expecting code to raise a throwable.
        at SoftAssertionsTest.lambda$test$0(SoftAssertionsTest.java:14)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at SoftAssertionsTest.test(SoftAssertionsTest.java:16)
[...]
```
However I would have expected something  like:
```
[ERROR] SoftAssertionsTest.test  Time elapsed: 0.086 s  <<< FAILURE!
java.lang.AssertionError: 
[A] 
Expecting code to raise a throwable.
        at SoftAssertionsTest.lambda$test$0(SoftAssertionsTest.java:14)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at SoftAssertionsTest.test(SoftAssertionsTest.java:16)
[...]
[B] 
Expecting code to raise a throwable.
        at SoftAssertionsTest.lambda$test$0(SoftAssertionsTest.java:14)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at SoftAssertionsTest.test(SoftAssertionsTest.java:16)
[...]
```

* assertj core version: 3.23.1
* java version: 17.0.3
* test framework version: JUnit 5.8.2

**Test case reproducing the bug**

```java
import java.util.function.Consumer;
import java.util.stream.Stream;

import org.assertj.core.api.SoftAssertions;
import org.junit.jupiter.api.Test;

class SoftAssertionsTest {

    @Test
    void test() {
        SoftAssertions softly = new SoftAssertions();
        Consumer<String> f = s -> softly.assertThatExceptionOfType(Exception.class)
                                        .as(s)
                                        .isThrownBy(this::checkSomething);

        Stream.of("A", "B").forEach(f);
        softly.assertAll();
    }

    private void checkSomething() {
    }
}
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this @stefanhh0, this is a bug indeed, the reason being we don't soft assert `hasBeenThrown` in `isThrownBy`: 
```java
  public ThrowableAssertAlternative<T> isThrownBy(final ThrowingCallable throwingCallable) {
    Throwable throwable = ThrowableAssert.catchThrowable(throwingCallable);
    assertThat(throwable).as(description).hasBeenThrown().isInstanceOf(expectedThrowableType);
    T castThrowable = (T) throwable;
    return buildThrowableTypeAssert(castThrowable).as(description);
  }
```

**Comment by stefanhh0** [comment]
Great, thanks for the Fix!
