### ISSUE TITLE
No getter for property for key in com.google.gson.internal.LinkedTreeMap

### ISSUE THREAD

**Issue by vishubhavsar** [assertj/assertj#2839]
#### Summary
When I am trying to extract the key which has period(.) in it, I am getting following error.

```
Can't find any field or property with name 'override-i-127'.
```

#### Example

```json
{
    "prefix-i-127.0.1.1": {
        "key": "value",
        "expired": "false",
        "submap": {
            "foo": "bar"
        }
    },
    "prefix-i-127.0.1.0": {
        "key": "value",
        "expired": "false",
        "submap": {
            "foo": "bar"
        }
    }
}
```

## Java

```java
softAssertions
    .assertThat(actualResponseMap)
    .extracting("prefix-i-127.0.1.0")
    .asInstanceOf(InstanceOfAssertFactories.map(String.class, Map.class))
    .isNotNull()
```

**Comment by scordio** [comment]
For a more effective investigation, could you please share a minimal example that shows how `actualResponseMap` is built?

**Comment by vishubhavsar** [comment]
Here's the complete TestNG test.

```java
import com.google.gson.Gson;
import org.testng.annotations.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

@Test
public void myTest() {
    final String inputString = """
            {
                "prefix-i-127.0.1.1": {
                    "key": "value",
                    "expired": "false",
                    "submap": {
                        "foo": "bar"
                    }
                },
                "prefix-i-127.0.1.0": {
                    "key": "value",
                    "expired": "false",
                    "submap": {
                        "foo": "bar"
                    }
                }
            }
            """;
    final Gson gson = new Gson();
    final Map<String, ?> map = gson.fromJson(inputString, Map.class);
    System.out.println("Map: " + map);
    assertThat(map).isNotNull(); // PASS
    /*
     Map is as below - 
     {prefix-i-127.0.1.1={key=value, expired=false, submap={foo=bar}}, prefix-i-127.0.1.0={key=value,
     expired=false, submap={foo=bar}}}
     */
    assertThat(map).containsKeys("prefix-i-127.0.1.1", "prefix-i-127.0.1.0"); // PASS
    assertThat(map)
            .extracting("prefix-i-127.0.1.1")
            .isNotNull(); // FAILS
}
```

Complete exception trace:

```
Can't find any field or property with name 'prefix-i-127'.
Error when introspecting properties was :
- No getter for property 'prefix-i-127' in com.google.gson.internal.LinkedTreeMap 
Error when introspecting fields was :
- Unable to obtain the value of the field <'prefix-i-127'> from <{prefix-i-127.0.1.1={key=value, expired=false, submap={foo=bar}}, prefix-i-127.0.1.0={key=value, expired=false, submap={foo=bar}}}>
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'prefix-i-127'.
Error when introspecting properties was :
- No getter for property 'prefix-i-127' in com.google.gson.internal.LinkedTreeMap 
Error when introspecting fields was :
- Unable to obtain the value of the field <'prefix-i-127'> from <{prefix-i-127.0.1.1={key=value, expired=false, submap={foo=bar}}, prefix-i-127.0.1.0={key=value, expired=false, submap={foo=bar}}}>
	at app//org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:91)
	at app//org.assertj.core.util.introspection.PropertyOrFieldSupport.getValueOf(PropertyOrFieldSupport.java:54)
	at app//org.assertj.core.extractor.ByNameSingleExtractor.apply(ByNameSingleExtractor.java:29)
	at app//org.assertj.core.api.AbstractAssert.extracting(AbstractAssert.java:1090)
	at app//org.assertj.core.api.AbstractObjectAssert.extracting(AbstractObjectAssert.java:835)
	...
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at app//org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at app//org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
	at app//org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
	at app//org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
	at app//org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at app//org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at app//org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base@17.0.4/java.util.ArrayList.forEach(ArrayList.java:1511)
	at app//org.testng.TestRunner.privateRun(TestRunner.java:806)
	at app//org.testng.TestRunner.run(TestRunner.java:601)
	at app//org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
	at app//org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
	at app//org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
	at app//org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at app//org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at app//org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at app//org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at app//org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at app//org.testng.TestNG.runSuites(TestNG.java:1099)
	at app//org.testng.TestNG.run(TestNG.java:1067)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.4/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.assertj.core.util.introspection.IntrospectionError: Unable to obtain the value of the field <'prefix-i-127'> from <{prefix-i-127.0.1.1={key=value, expired=false, submap={foo=bar}}, prefix-i-127.0.1.0={key=value, expired=false, submap={foo=bar}}}>
	at app//org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:248)
	at app//org.assertj.core.util.introspection.FieldSupport.fieldValue(FieldSupport.java:202)
	at app//org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:75)
	... 51 more
Caused by: java.lang.IllegalArgumentException: Cannot locate field prefix-i-127 on class com.google.gson.internal.LinkedTreeMap
	at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:129)
	at org.assertj.core.util.introspection.FieldUtils.readField(FieldUtils.java:144)
	at org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:208)
	... 53 more
```

**Comment by scordio** [comment]
Thank you, @vishubhavsar, I'll look into it.

**Comment by joel-costigliola** [comment]
The reason is we treat field name like `a.b` as a field `a` that has a field `b`.

There is no way to escape the `.` at the moment, something we have to talk about with the team.

If you want to assert JSON data, we recommend using https://github.com/lukas-krecan/JsonUnit
