### ISSUE TITLE
Comparassion between two TimeZone object throws error

### ISSUE THREAD

**Issue by jsolferreira** [assertj/assertj#2891]
**Describe the bug**
When comparing two TimeZone objects using recursive comparison it throws the following error:
```
Can't find any field or property with name 'dirty'.
Error when introspecting properties was :
- Unable to find property 'dirty' in sun.util.calendar.ZoneInfo 
Error when introspecting fields was :
- Unable to obtain the value of the field <'dirty'> from <sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]>
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'dirty'.
Error when introspecting properties was :
- Unable to find property 'dirty' in sun.util.calendar.ZoneInfo 
Error when introspecting fields was :
- Unable to obtain the value of the field <'dirty'> from <sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]>
	at app//org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:91)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.dualValueForField(RecursiveComparisonConfiguration.java:693)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.lambda$getActualFieldNamesToCompare$4(RecursiveComparisonConfiguration.java:671)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base@17.0.5/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.getActualFieldNamesToCompare(RecursiveComparisonConfiguration.java:677)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator$ComparisonState.initDualValuesToCompare(RecursiveComparisonDifferenceCalculator.java:127)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator$ComparisonState.access$100(RecursiveComparisonDifferenceCalculator.java:72)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:217)
	at app//org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:208)
	at app//org.assertj.core.api.RecursiveComparisonAssert.determineDifferencesWith(RecursiveComparisonAssert.java:1374)
	at app//org.assertj.core.api.RecursiveComparisonAssert.isEqualTo(RecursiveComparisonAssert.java:158)
```

* assertj core version: 3.23.1
* java version: 17

**Test case reproducing the bug**

```java
@Test
public void test() {

    TimeZone timeZone1 = TimeZone.getTimeZone("UTC");
    TimeZone timeZone2 = TimeZone.getTimeZone("UTC");

    assertThat(timeZone1)
        .usingRecursiveComparison()
        .isEqualTo(timeZone2);
}
```

**Comment by scordio** [comment]
Thanks for the bug report, @jsolferreira! This will be fixed in 3.24.0.
