### ISSUE TITLE
InaccessibleObjectException with usingRecursiveComparison on MockHttpServletResponse

### ISSUE THREAD

**Issue by thomasredlin** [assertj/assertj#2927]
I'm currently upgrading our project from Java 11 to 17. Some tests are failing when comparing two instances of `org.springframework.mock.web.MockHttpServletResponse` with `usingRecursiveComparison`, there is an `InaccessibleObjectException`.

We're using:
Java 17
AssertJ Core 3.24.2 (also reproducible with 3.21.0)
Spring Boot 2.6.6

```java
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'formatter'.
Error when introspecting properties was :
- No getter for property 'formatter' in org.springframework.mock.web.MockHttpServletResponse$ResponsePrintWriter 
Error when introspecting fields was :
- Unable to obtain the value of the field <'formatter'> from <org.springframework.mock.web.MockHttpServletResponse$ResponsePrintWriter@3f67593e>

	at org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:91)
	at org.assertj.core.api.recursive.comparison.DefaultRecursiveComparisonIntrospectionStrategy.getChildNodeValue(DefaultRecursiveComparisonIntrospectionStrategy.java:38)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.getValue(RecursiveComparisonConfiguration.java:688)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.dualValueForField(RecursiveComparisonConfiguration.java:704)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.lambda$getActualChildrenNodeNamesToCompare$5(RecursiveComparisonConfiguration.java:673)
	...
Caused by: org.assertj.core.util.introspection.IntrospectionError: Unable to obtain the value of the field <'formatter'> from <org.springframework.mock.web.MockHttpServletResponse$ResponsePrintWriter@3f67593e>
	at org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:248)
	at org.assertj.core.util.introspection.FieldSupport.fieldValue(FieldSupport.java:202)
	at org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:75)
	... 95 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.util.Formatter java.io.PrintWriter.formatter accessible: module java.base does not "opens java.io" to unnamed module @14a2f921
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.assertj.core.util.introspection.FieldUtils.getField(FieldUtils.java:67)
	at org.assertj.core.util.introspection.FieldUtils.readField(FieldUtils.java:143)
	at org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:208)
	... 97 more
```

Example

```java
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletResponse;

import java.io.ByteArrayOutputStream;

import static org.assertj.core.api.Assertions.assertThat;

public class RecursiveComparisonTest {

  @Test
  public void recursiveComparisonTest() {
    MockHttpServletResponse response1 = new MockHttpServletResponse();
    MockHttpServletResponse response2 = new MockHttpServletResponse();

    assertThat(response1).usingRecursiveComparison()
        .withEqualsForType((b1, b2) -> b1.toString().equals(b2.toString()), ByteArrayOutputStream.class)
        // .ignoringFields("writer")
        .isEqualTo(response2);
  }
}
```

When using the `ignoringFields` line, it's working.

Note that I need the `equalsForType` for `ByteArrayOutputStream` due to AssertJ using Object equals for Java 17 since version 3.23.0

Also, `ignoringExpectedNullFields()` doesn't seem to work here.

**Comment by joel-costigliola** [comment]
Thanks for reporting this @thomasredlin.

**Comment by joel-costigliola** [comment]
The recursive comparison avoids introspecting java types, it uses the type equals method to compare them.
To detect a java type, it looks at the class package and checks if it starts with `java.`, `javax.`, `sun.` or `com.sun.` This is not enough for `MockHttpServletResponse.ResponsePrintWriter` because `ResponsePrintWriter` is defined in `org.springframework.mock.web` but inherits a java type `PrintWriter` which is then introspected (the recursive comparison checks inherited fields).

Since java 17, we can't introspect java types so I think we will need to consider any type inheriting a java type as to be compared with their equals method, I don't see an easy way to compare fields from the non java type and use the equals method to compare the inherited fields that belong to a java type. This kinda relates to https://github.com/assertj/assertj/issues/2812

**Comment by joel-costigliola** [comment]
> Note that I need the equalsForType for ByteArrayOutputStream due to AssertJ using Object equals for Java 17 since version 3.23.0

`ByteArrayOutputStream` being a java type, we can't introspect it and thus compare them with their `equals` method (which is not overridden so compare references), so you were right to register a specific way to compare them with `withEqualsForType`
