### ISSUE TITLE
usingRecursiveAssertion() field !=null-check fails for byte[] (java) / ByteArray(kotlin)

### ISSUE THREAD

**Issue by oyvindma** [assertj/assertj#3045]
**Describe the bug**
Verifying that a field of type byte[] is not null fails with `IllegalArgumentException: Given object null is not an array` when using both` .hasNoNullFields()` and `.allFieldsSatisfy(o -> o != null);`. Both for byte[] in java and ByteArray in Kotlin.

* assertj core version: 3.24.2
* java version: java/11.0.16.1-tem/
* test framework version: junit-jupiter-api 5.9.2
* os (if relevant): Both linux and windows

**Test case reproducing the bug**

Add a test case showing the bug that we can run

```java
package org.example;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

class TestCase{
    class Outer{
        Inner inner = new Inner();
        byte[] byteArrayOuter = null;
    }

    class Inner{
        byte[] byteArray = null;
    }

    /**
     * Fails as expected with:
     *  Expecting
     *  org.example.TestCase$Outer@c03cf28
     *  not to have any null property or field, but "byteArrayOuter" was null.
     */
    @Test
    public void  outerAssertionCompletesWithExpectedAssertionError(){
        assertThat(new Outer()).hasNoNullFieldsOrProperties();
    }

    /**
     * Fails with the following error:
     * /home/oyvasb/.sdkman/candidates/java/11.0.16.1-tem/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/snap/intellij-idea-ultimate/426/lib/idea_rt.jar=42217:/snap/intellij-idea-ultimate/426/bin -Dfile.encoding=UTF-8 -classpath /home/oyvasb/.m2/repository/org/junit/platform/junit-platform-launcher/1.9.2/junit-platform-launcher-1.9.2.jar:/home/oyvasb/.m2/repository/org/junit/platform/junit-platform-engine/1.9.2/junit-platform-engine-1.9.2.jar:/home/oyvasb/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.9.2/junit-jupiter-engine-5.9.2.jar:/snap/intellij-idea-ultimate/426/lib/idea_rt.jar:/snap/intellij-idea-ultimate/426/plugins/junit/lib/junit5-rt.jar:/snap/intellij-idea-ultimate/426/plugins/junit/lib/junit-rt.jar:/home/oyvasb/kode/assertj-nullcheckerror/target/test-classes:/home/oyvasb/kode/assertj-nullcheckerror/target/classes:/home/oyvasb/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.9.2/junit-jupiter-api-5.9.2.jar:/home/oyvasb/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/oyvasb/.m2/repository/org/junit/platform/junit-platform-commons/1.9.2/junit-platform-commons-1.9.2.jar:/home/oyvasb/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/home/oyvasb/.m2/repository/org/assertj/assertj-core/3.24.2/assertj-core-3.24.2.jar:/home/oyvasb/.m2/repository/net/bytebuddy/byte-buddy/1.12.21/byte-buddy-1.12.21.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit5 org.example.TestCase,outerAssertionFailsForByteArray
     *
     * java.lang.IllegalArgumentException: Given object null is not an array
     *
     * 	at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:131)
     * 	at org.assertj.core.util.Arrays.asObjectArray(Arrays.java:57)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoArray(RecursiveAssertionDriver.java:166)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.doRecursionForSpecialTypes(RecursiveAssertionDriver.java:147)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:122)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.lambda$evaluateFieldsOfCurrentNodeRecursively$2(RecursiveAssertionDriver.java:238)
     * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.evaluateFieldsOfCurrentNodeRecursively(RecursiveAssertionDriver.java:237)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:125)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.lambda$evaluateFieldsOfCurrentNodeRecursively$2(RecursiveAssertionDriver.java:238)
     * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.evaluateFieldsOfCurrentNodeRecursively(RecursiveAssertionDriver.java:237)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:125)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     * 	at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertOverObjectGraph(RecursiveAssertionDriver.java:56)
     * 	at org.assertj.core.api.RecursiveAssertionAssert.allFieldsSatisfy(RecursiveAssertionAssert.java:114)
     * 	at org.assertj.core.api.RecursiveAssertionAssert.hasNoNullFields(RecursiveAssertionAssert.java:168)
     * 	at org.example.TestCase.outerAssertionFailsForByteArray(TestCase.java:31)
     * 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     * 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     * 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     * 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     * 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
     * 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
     * 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
     * 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
     * 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
     * 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
     * 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
     * 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
     * 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
     * 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
     * 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
     * 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
     * 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
     * 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
     * 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
     * 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
     * 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     * 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     * 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     * 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     * 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     * 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     * 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     * 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     * 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     * 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
     * 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
     * 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
     * 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
     * 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
     * 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
     * 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
     * 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
     * 	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
     * 	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
     * 	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
     * 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
     * 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
     * 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
     *
     * Process finished with exit code 255
     */
    @Test
    public void outerAssertionFailsForByteArray(){
        assertThat(new Outer())
                .usingRecursiveAssertion()
                .hasNoNullFields();
    }


    /**
     * Fails with the following error:
     * java.lang.IllegalArgumentException: Given object null is not an array
     *
     *      at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:131)
     *      at org.assertj.core.util.Arrays.asObjectArray(Arrays.java:57)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoArray(RecursiveAssertionDriver.java:166)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.doRecursionForSpecialTypes(RecursiveAssertionDriver.java:147)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:122)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.lambda$evaluateFieldsOfCurrentNodeRecursively$2(RecursiveAssertionDriver.java:238)
     *      at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.evaluateFieldsOfCurrentNodeRecursively(RecursiveAssertionDriver.java:237)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:125)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.lambda$evaluateFieldsOfCurrentNodeRecursively$2(RecursiveAssertionDriver.java:238)
     *      at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.evaluateFieldsOfCurrentNodeRecursively(RecursiveAssertionDriver.java:237)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.recurseIntoFieldsOfCurrentNode(RecursiveAssertionDriver.java:125)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertRecursively(RecursiveAssertionDriver.java:74)
     *      at org.assertj.core.api.recursive.assertion.RecursiveAssertionDriver.assertOverObjectGraph(RecursiveAssertionDriver.java:56)
     *      at org.assertj.core.api.RecursiveAssertionAssert.allFieldsSatisfy(RecursiveAssertionAssert.java:114)
     *      at org.assertj.core.api.RecursiveAssertionAssert.hasNoNullFields(RecursiveAssertionAssert.java:168)
     *      at org.example.TestCase.innerAssertionfailsforByteArray(TestCase.java:35)
     *      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     *      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     *      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     *      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     *      at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
     *      at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
     *      at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
     *      at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
     *      at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
     *      at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
     *      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
     *      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
     *      at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
     *      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
     *      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
     *      at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
     *      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
     *      at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
     *      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
     *      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
     *      at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     *      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     *      at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     *      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     *      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     *      at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
     *      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
     *      at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
     *      at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
     *      at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
     *      at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
     *      at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
     *      at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
     *      at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
     *      at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
     *      at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
     *      at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
     *      at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
     *      at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
     *      at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
     *      at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
     *      at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
     *      at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
     *      at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
     */
    @Test
    public void innerAssertionFailsForByteArray(){
        assertThat(new Outer())
                .usingRecursiveAssertion()
                .allFieldsSatisfy(o -> o != null);
    }
}
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this with details @oyvindma!

**Comment by oyvindma** [comment]
To find the situations i placed a breakpoint with coindition "expression==false" on line 130 in Preconditions.checkArgument(...). 

```
  public static void checkArgument(boolean expression, String errorMessageTemplate, Object... errorMessageArgs) {
//Here
    if (!expression) throw new IllegalArgumentException(format(errorMessageTemplate, errorMessageArgs));
  }
  ```

**Comment by joel-costigliola** [comment]
I have fixed the bug and clarified a bit how the recursive assertion works in the javadoc.

Note that by default recursive assertion does not apply the predicate on collections, arrays, maps and optionals but only on their values, this can be changed with 

* `withCollectionAssertionPolicy(RecursiveAssertionConfiguration.CollectionAssertionPolicy)` for collections and arrays
* `withMapAssertionPolicy(RecursiveAssertionConfiguration.MapAssertionPolicy)` for maps
* `withOptionalAssertionPolicy(RecursiveAssertionConfiguration.OptionalAssertionPolicy)` for optionals
