### ISSUE TITLE
OOME while just trying to assert long array.length

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#3065]
**Describe the bug**

Given, an instance of `byte[]` whose length is, incidentally, `98007000`,
I tried to verify its length.

```java
final var bytes = getBytes();
final var expectedSize = whatever-not-98007000;
assertThat(bytes).isNotNull().hasSize(expectedSize);
```

And an `OutOfMermoryError` thrown, seems it tried to create a nice message.

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.Integer.toString(Integer.java:457)
	at java.base/java.lang.Byte.toString(Byte.java:441)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:348)
	at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:250)
	at org.assertj.core.presentation.StandardRepresentation.safeStringOf(StandardRepresentation.java:621)
	at org.assertj.core.presentation.StandardRepresentation.lambda$representElements$0(StandardRepresentation.java:628)
	at org.assertj.core.presentation.StandardRepresentation$$Lambda$508/0x00000008003b4a40.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
```

**Comment by etellman** [comment]
Here's what I came up with: https://github.com/assertj/assertj/pull/3109. Let me know what you think of the approach.

This is my first open source contribution, so I may have messed something up with the logistics. Also me know if I created the pull request correctly, etc.
