### ISSUE TITLE
NPE with `extracting(Function... extractors)`

### ISSUE THREAD

**Issue by stanio** [assertj/assertj#3375]
Assertions using `extracting(Function... extractors)` over an actual `null` object/reference fail with `NullPointerException`:

```
java.lang.NullPointerException
	at org.assertj.core.api.AbstractObjectAssert.lambda$extractingForProxy$0(AbstractObjectAssert.java:926)
	at java.base/...
	at org.assertj.core.api.AbstractObjectAssert.extractingForProxy(AbstractObjectAssert.java:927)
	at org.assertj.core.api.AbstractObjectAssert.extracting(AbstractObjectAssert.java:917)
```

* assertj core version: 3.25.3
* java version: 8, 11, 17, 21
* test framework version: junit5

**Test case reproducing the bug**

```java
import static org.assertj.core.api.Assertions.assertThat;

import java.awt.geom.Point2D;

import org.junit.jupiter.api.Test;

    @Test
    void verifyCoordinates() {
        Point2D point = null; //new Point(5, 3);
    
        assertThat(point).as("point")
                .extracting(Point2D::getX, Point2D::getY)
                .as("x, y")
                .containsExactly(5.0, 3.0);
    }
```

For comparison, using `extracting(String... propertiesOrFields)`:

```java
    assertThat(point).as("point")
            .extracting("x", "y")
            .as("x, y")
            .containsExactly(5.0, 3.0);
```

yields:

```
java.lang.IllegalArgumentException: The object to extract fields/properties from should not be null
	at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:131)
	at org.assertj.core.extractor.ByNameMultipleExtractor.apply(ByNameMultipleExtractor.java:36)
	at org.assertj.core.extractor.ByNameMultipleExtractor.apply(ByNameMultipleExtractor.java:24)
	at org.assertj.core.api.AbstractObjectAssert.extracting(AbstractObjectAssert.java:789)
```

I think the former usage should match the latter behavior.

**Comment by stanio** [comment]
I have found the following related issues: https://github.com/assertj/assertj/issues/2392#issuecomment-961969975, #2401, #2495.  Not sure if the last is meant to address this more specific one.

**Comment by joel-costigliola** [comment]
I agree we could be more consistent there

**Comment by Illutax** [comment]
This looks like it was already fixed on `main`, just without a link back to this issue.

`AbstractObjectAssert.doExtracting(Function[])` now guards `actual` before applying the extractors:

```java
protected AbstractListAssert<?, List<?>, Object, ObjectAssert<Object>> doExtracting(Function<? super ACTUAL, ?>[] extractors) {
  requireNonNull(extractors, shouldNotBeNull("extractors")::create);
  isNotNull("extracting");
  ...
}
```

The `isNotNull` call came in with d4ded1a1c4fd5e84e0b165ff65b160cf05e1de51 ("Skip assertions in soft assertion mode when a soft null-guard in navigation method fails"), and 1540ebb30c6b5057f7436deed958b67b030a57fc later added the contextual `[extracting]` description. Neither commit referenced this issue, which is probably why it stayed open.

It is covered by a test as well — `ObjectAssert_extracting_with_Function_Array_Test`:

```java
@Test
void should_throw_an_AssertionError_with_contextual_description_if_actual_is_null() {
  // GIVEN
  Employee nullEmployee = null;
  // WHEN
  var assertionError = expectAssertionError(() -> assertThat(nullEmployee).extracting(FIRST_NAME, Employee::getName));
  // THEN
  then(assertionError).hasMessageContainingAll("[extracting]", actualIsNull());
}
```

I also walked the rest of the family on `main` — `extracting`, `extractingResultOf`, `map`, `flatMap`, `flatExtracting`, `extractingByKey(s)` and `extractingFromEntries` across `AbstractObjectAssert`, `AbstractIterableAssert`, `AbstractMapAssert`, `AbstractAssert` and `AbstractOptionalAssert`. Every public entry point reaches an `isNotNull(<methodName>)` guard, either directly or via `internalMap` / `internalFlatMap` / a `doXxx` helper. I couldn't find a remaining path where a null `actual` slips through to the extractors. Noice.

So this issue can probably be closed as fixed in 4.0.0.

Two things that might still be worth a word from a maintainer:

1. **Is 4.0.0 the intended vehicle, or is a 3.x backport on the table?** The behaviour change (`NullPointerException` → `AssertionError`) is the same kind of breaking change that #2401 was labelled with back in 2021, so 4.0.0-only seems deliberate — but it means everyone on the 3.x line still hits the NPE today. Confirming that here would save the next person the same archaeology.

2. **One detail that makes the 3.x behaviour worse than the issue title suggests**, in case it affects how this gets prioritised: with a *method-reference* extractor — the form the Javadoc examples use — there is no message at all. Measured on 3.27.7 / JDK 25:

   | Expression | Result on 3.27.7 |
   |---|---|
   | `assertThat(null).extracting(Person::name, Person::age)` | `NullPointerException: null` |
   | `assertThat(null).extracting(p -> p.name(), p -> p.age())` | `NullPointerException: Cannot invoke "Person.name()" because "<parameter1>" is null` |

   JEP 358 helpful messages do not kick in for the method-reference form, because the throwing frame lives in a `LambdaMetafactory` hidden class. On top of that, the topmost stack frame is `java.util.stream.ReferencePipeline$3$1.accept`, so the user's own test line sits below a stack of AssertJ frames. That is what made it hard to diagnose in practice.

Also relates to: [Issue 2401](https://github.com/assertj/assertj/issues/2401)

**Comment by scordio** [comment]
Thanks for flagging, @Illutax.

> JEP 358 helpful messages do not kick in for the method-reference form, because the throwing frame lives in a `LambdaMetafactory` hidden class. On top of that, the topmost stack frame is `java.util.stream.ReferencePipeline$3$1.accept`, so the user's own test line sits below a stack of AssertJ frames. That is what made it hard to diagnose in practice.

This might be an improvement to consider. We'll review this and the general issue closure as part of 4.0.0-M3.
