### ISSUE TITLE
SoftAssertions#fail(String failureMessage, Throwable realCause) display information about realCause?

### ISSUE THREAD

**Issue by PascalSchumacher** [assertj/assertj#864]
While taking a look at https://github.com/joel-costigliola/assertj-core/issues/539 I noticed that SoftAssertions#fail(String failureMessage, Throwable realCause) could be more useful, at the moment it does not show any information about realCause.

```java
@Test
public void test() {
    softly.fail("failure", new RuntimeException("abc"));
    softly.assertAll();
}
```

just displays:

>org.assertj.core.api.SoftAssertionError:
>The following assertion failed:
>1) failure
>
>    at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:116)
>    at org.assertj.core.api.SoftAssertionsTest.test(SoftAssertionsTest.java:115)

The error message etc. of `realCause` is lost.

**Comment by joel-costigliola** [comment]
I agree, we should at least display the real cause message and probably the stack trace (although it might get more difficult to read the other errors because of a stack trace can be quite long).
WDYT ?

**Comment by PascalSchumacher** [comment]
The real cause message (without the stacktrace) would be the best compromise between being concise and providing helpful information. (Stacktrace can also be added later on if there is demand for this feature.)

**Comment by joel-costigliola** [comment]
What about displaying the 5 first stack trace elements (and adding the fact that it is a truncated stack trace) ?

**Comment by PascalSchumacher** [comment]
Sure, that should be enough information in almost all cases I guess.

**Comment by sherfert** [comment]
I think this regressed. While it seems the behavior was fixed in 3.23.1 (https://github.com/assertj/assertj/commit/c487af4cdb37b01103e4ec0f9971c9a53c766db5), I can reproduce the original issue in 3.27.6.

**Comment by sherfert** [comment]
After having digged a bit, I think this does not work if we succeed in creating a `org.opentest4j.MultipleFailuresError` in `AssertionErrorCreator`

```
public AssertionError multipleSoftAssertionsError(List<? extends Throwable> errors) {
    Optional<AssertionError> multipleFailuresError = tryBuildingMultipleFailuresError(errors);
    return multipleFailuresError.orElse(new SoftAssertionError(describeErrors(errors)));
  }
```

The or-else-returned `SoftAssertionError` still calls `describeErrors` introduced in the above linked commit.

**Comment by scordio** [comment]
Thanks for reporting it, @sherfert! I'll add it to 3.28.0 for analysis.

**Comment by joel-costigliola** [comment]
I did some work on the 4.x branch related to this issue in 452cee73 (see https://github.com/assertj/assertj/commit/452cee73b0f87d6f893a1bdc6bb9bd394e9466fb#diff-c26c251712cc3e05ac3403ef16c259f1595b120d5bfd7b297cf9c05bf0490596 for examples).

@sherfert I would be more confident if you could provide an example of what goes wrong so that I can try it on 4.x, would that be possible for you to provide such an example ?

**Comment by sherfert** [comment]
I think the issue description says it all, actually. But let me provide a unit test: (adapted from the test added in c487af4cdb37b01103e4ec0f9971c9a53c766db5)

```java
    @Test
    public void shouldDisplayTheErrorCauseAndTheCauseFirstStackTraceElements() {
        assertThatThrownBy(() -> {
                    SoftAssertions softly = new SoftAssertions();
                    try {
                        throw new RuntimeException("abc");
                    } catch (RuntimeException e) {
                        softly.fail("def", e);
                    }
                    softly.assertAll();
                })
                .isInstanceOf(AssertionError.class)
                .hasMessageStartingWith(format("%nThe following assertion failed:%n" + "1) def"))
                .hasMessageContaining(format(
                        "cause message: abc%n" + "cause first five stack trace elements:%n" + "\tat %s.",
                        this.getClass().getName()));
    }
```

This test fails:

```
java.lang.AssertionError: 
Expecting actual:
  "
Multiple Failures (1 failure)
-- failure 1 --def
at VerboseSoftAssertionsTest.lambda$shouldDisplayTheErrorCauseAndTheCauseFirstStackTraceElements$0(VerboseSoftAssertionsTest.java:36)"
to start with:
  "
The following assertion failed:
1) def"
```

Obviously it does so also because of formatting difference between `SoftAssertionError` and `MultipleFailuresError`, but the main part is that I want both the message of the original exception (i.e. "abc") and it's stack trace to be included in the `AssertionError` raised from `assertAll()`.

I make this test pass by changing the implementation of `assertAll()` to be 

```java
    public void assertAll() {
        List<AssertionError> errors = assertionErrorsCollected();
        if (!errors.isEmpty()) {
            throw new SoftAssertionError(describeErrors(errors));
        }
    }
````

I hope this clarifies.

**Comment by joel-costigliola** [comment]
Alright, trying this test in 4.x/main
```java
  @Test
  public void shouldDisplayTheErrorCauseAndTheCauseFirstStackTraceElements() {
    SoftAssertions softly = new SoftAssertions();
    try {
      throw new RuntimeException("abc");
    } catch (RuntimeException e) {
      softly.fail("def", e);
    }
    softly.assertAll();
  }
```
fails with the following error message:
```
org.assertj.core.error.MultipleAssertionsError: 1 assertion error:

-- error 1 --
def
cause message: abc
cause first 3 stack trace elements:
	at org.assertj.core@4.0.0-SNAPSHOT/org.example.test.MultipleAssertionsError_getMessage_Test.shouldDisplayTheErrorCauseAndTheCauseFirstStackTraceElements(MultipleAssertionsError_getMessage_Test.java:256)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
```
which I believe is what you expect, right ?

**Comment by sherfert** [comment]
Yes @joel-costigliola that looks great!
